server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.01:8761/eureka
## fetch-registry : Eureka ????? ?????? ??? ????? ??? ??? ???? ??
## service-url defaultZone : ???? ??? ??